---

- name: get lvm partition info
  become: yes
  parted:
    device: /dev/sda
    state: info
    unit: KiB
  register: sda_info
  tags:
    - disk
    - never
    - experimental

- name: create partition
  become: yes
  parted:
    device: /dev/sda
    state: present
    unit: KiB
    number: 3
    flags:
      - lvm
    part_start: "{{ sda_info.partitions[-1].end }}KiB"
  tags:
    - disk
    - never
    - experimental

- name: create a volume group
  become: yes
  lvg:
    vg: vgvagrant
    pvs: /dev/sda3,/dev/sda5
  tags:
    - disk
    - never
    - experimental

- name: resize logical volume
  become: yes
  lvol:
    vg: vgvagrant
    lv: root
    resizefs: yes
    size: +100%FREE
  tags:
    - disk
    - never
    - experimental
