---

- name: install bash-completion
  become: yes
  ansible.builtin.yum:
    state: present
    name:
      - bash-completion
  tags:
    - dotfiles

- name: install dotfiles
  ansible.builtin.shell: |
    set -o pipefail
    curl -L http://bit.ly/rinatz-dotfiles | bash
  args:
    executable: /bin/bash
    warn: no
  register: result
  changed_when: result.rc == 0
  tags:
    - dotfiles
