---
- name: install bash-completion
  become: true
  ansible.builtin.apt:
    name: bash-completion
    state: present
    update_cache: true
    cache_valid_time: 3600
  tags:
    - dotfiles

- name: install dotfiles
  ansible.builtin.shell: |
    set -o pipefail
    curl -L http://bit.ly/rinatz-dotfiles | bash
  args:
    executable: /bin/bash
    warn: no
  register: result
  changed_when: result.rc == 0
  tags:
    - dotfiles
