---
- name: Install direnv
  become: true
  ansible.builtin.get_url:
    url: https://github.com/direnv/direnv/releases/download/v{{ direnv_version }}/direnv.linux-arm64
    dest: /usr/local/bin/direnv
    mode: 0755
  tags:
    - direnv
