---
- name: Install stow
  become: true
  ansible.builtin.yum:
    state: present
    name:
      - stow
  tags:
    - stow

- name: Create directory
  become: true
  ansible.builtin.file:
    path: /usr/local/stow
    state: directory
    mode: 0755
  tags:
    - stow
