---
- name: Install stow
  become: true
  ansible.builtin.apt:
    name: stow
    state: present
    update_cache: true
    cache_valid_time: 3600
  tags:
    - stow

- name: Create directory
  become: true
  ansible.builtin.file:
    path: /usr/local/stow
    state: directory
    mode: 0755
  tags:
    - stow
