---
- name: add apt key
  become: true
  ansible.builtin.apt_key:
    url: https://apt.kitware.com/keys/kitware-archive-latest.asc
    state: present
  tags:
    - cmake

- name: add apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb https://apt.kitware.com/ubuntu/ {{ ansible_distribution_release }} main
    filename: cmake
    state: present
  tags:
    - cmake

- name: install cmake
  become: true
  ansible.builtin.apt:
    name: cmake
    state: present
    update_cache: true
    cache_valid_time: 3600
  tags:
    - cmake
