---
- name: clone
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: ~/.fzf
    depth: 1
    version: "{{ fzf_version }}"
  tags:
    - fzf

- name: install
  ansible.builtin.command: ~/.fzf/install --all
  register: result
  changed_when: result.rc == 0
  tags:
    - fzf
