---

- name: add apt repository
  become: yes
  ansible.builtin.apt_repository:
    repo: 'ppa:git-core/ppa'
  tags:
    - scm

- name: install packages
  become: yes
  ansible.builtin.apt:
    state: present
    update_cache: yes
    cache_valid_time: 3600
    name:
      - git
      - openssh-client
      - procps
  tags:
    - scm
