---
- name: add apt repository
  become: true
  ansible.builtin.apt_repository:
    repo: "ppa:git-core/ppa"
  tags:
    - scm

- name: install packages
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: true
    cache_valid_time: 3600
    name:
      - git
      - openssh-client
      - procps
  tags:
    - scm
