---

- name: "download"
  become: yes
  unarchive:
    src: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"
    dest: /usr/local/stow
    remote_src: yes
  tags:
    - go

- name: stow
  become: yes
  command: stow go
  args:
    chdir: /usr/local/stow
  register: result
  changed_when: result.rc == 0
  tags:
    - go
