---

- name: install node
  ansible.builtin.shell: |
    set -o pipefail
    curl https://get.volta.sh | bash
    ~/.volta/bin/volta install node
  args:
    executable: /bin/bash
    warn: no
  register: result
  changed_when: result.rc == 0
  tags:
    - node
