---

- name: install docker
  become: yes
  ansible.builtin.command: amazon-linux-extras install -y docker
  register: result
  changed_when: result.rc == 0
  tags:
    - docker

- name: add user to docker group
  become: yes
  ansible.builtin.command: usermod -aG docker "{{ ansible_user_id }}"
  register: result
  changed_when: result.rc == 0
  tags:
    - docker

- name: start docker service
  become: yes
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker
