---

- name: add apt key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: add apt repository
  become: yes
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    filename: docker
    state: present
  tags:
    - docker

- name: install docker
  become: yes
  apt:
    name: docker-ce
    state: present
    update_cache: yes
    cache_valid_time: 3600
  tags:
    - docker

- name: add user to docker group
  become: yes
  command: usermod -aG docker "{{ ansible_user_id }}"
  register: result
  changed_when: result.rc == 0
  tags:
    - docker

- name: start docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: yes
  tags:
    - docker

- name: create directory
  become: yes
  file:
    path: /usr/local/libexec/docker/cli-plugins
    state: directory
    mode: 0755
  tags:
    - docker

- name: install compose
  become: yes
  get_url:
    url: https://github.com/docker/compose/releases/download/v{{ compose_version }}/docker-compose-{{ ansible_system | lower }}-{{ ansible_machine }}
    dest: /usr/local/libexec/docker/cli-plugins/docker-compose
    mode: 0755
  tags:
    - docker

- name: symlink
  become: yes
  file:
    src: /usr/local/libexec/docker/cli-plugins/docker-compose
    dest: /usr/local/bin/docker-compose
    state: link
  tags:
    - docker
