---
- name: Install starship
  become: true
  ansible.builtin.shell: |
    set -o pipefail
    curl -fsSL https://starship.rs/install.sh | sh -s -- -y
  args:
    executable: /bin/bash
    warn: no
  register: result
  changed_when: result.rc == 0
  tags:
    - starship
